name: scout_service

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: scout_service_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - scout-network

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/scout_service_development
      RAILS_ENV: development
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true
    command: bash -c "
      bundle install &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create db:migrate db:seed &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - scout-network

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/scout_service_test
      RAILS_ENV: test
      SECRET_KEY_BASE: "4eca4755a401ee95ec2029fb59c92a9c5630af7b9e6a7b25cc69c2669e963ded87429300ce8a13889bdf97cd0dbfe5a197dbf8451e71cd45db474e638454be82"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "
      bundle install &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create db:migrate"
    networks:
      - scout-network

volumes:
  postgres_data:
  bundle_cache:

networks:
  scout-network:
    driver: bridge
