version: "3.8"
name: scout_service

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: scout_service_development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/scout_service_development
      RAILS_ENV: development
    depends_on:
      db:
        condition: service_healthy
    tty: true
    stdin_open: true
    command: bash -c "
      bundle install &&
      rm -f tmp/pids/server.pid &&
      bundle exec rails db:create db:migrate db:seed &&
      bundle exec rails s -p 3000 -b '0.0.0.0'"

volumes:
  postgres_data:
  bundle_cache:
